// -*- Mode: C++; -*-
// TinyCl - XML - Symbols
// xml_syms.inc
//
// Copyright (C) 2007-2008 by Project Vogue.
// Written by Yoshifumi   "VOGUE" INOUE. (yosi@msn.com)
//
// @(#)$Id: //proj/evedit2/mainline/tinycl/tinycl_syms.inc#55 $
//

// [DOM *]
defexternal(dom, dom_Punspecified_namespaceP,
    "+UNSPECIFIED-NAMESPACE+" )

// [DOM *]
definternal(dom, dom_Anamespace_tableA,         "*NAMESPACE-TABLE*")

// [DOM A]
defexternal(dom, dom_append_child,              "APPEND-CHILD")
defexternal(dom, dom_attribute,                 "ATTRIBUTE")
defexternal(dom, dom_attribute_node,            "ATTRIBUTE-NODE")
// [DOM C]
defexternal(dom, dom_cdata_section,             "CDATA-SECTION")
defexternal(dom, dom_character_data,            "CHARACTER-DATA")
defexternal(dom, dom_child_nodes,               "CHILD-NODES")
defexternal(dom, dom_comment,                   "COMMENT")
// [DOM D]
definternal(dom, dom_data,                      "DATA")
defexternal(dom, dom_document,                  "DOCUMENT")
defexternal(dom, dom_document_element,          "DOCUMENT-ELEMENT")
defexternal(dom, dom_document_fragment,         "DOCUMENT-FRAGMENT")
defexternal(dom, dom_dom_error,                 "DOM-ERROR")
// [DOM E]
defexternal(dom, dom_element,                   "ELEMENT")
defexternal(dom, dom_entity_reference,          "ENTITY-REFERENCE")
defexternal(dom, dom_expanded_name,             "EXPANDED-NAME")
definternal(dom, dom_expanded_table,            "EXPANDED-TABLE")
// [DOM F]
defexternal(dom, dom_first_child,               "FIRST-CHILD")
definternal(dom, dom_flags,                     "FLAGS")
definternal(dom, dom_floating_node,             "FLOATING-NODE")
// [DOM H]
defexternal(dom, dom_hierachy_error,
    "HIERACHY-ERROR" )
// [DOM I]
defexternal(dom, dom_insert_after,              "INSERT-AFTER")
defexternal(dom, dom_insert_before,             "INSERT-BEFORE")
defexternal(dom, dom_invalid_character,
    "INVALID-CHARACTER" )
defexternal(dom, dom_invalid_modification,
    "INVALID-MODIFICATION" )
// [DOM L]
defexternal(dom, dom_last_child,                "LAST-CHILD")
defexternal(dom, dom_local_name,                "LOCAL-NAME")
// [DOM M]
defexternal(dom, dom_make_attribute,            "MAKE-ATTRIBUTE")
defexternal(dom, dom_make_document,             "MAKE-DOCUMENT")
defexternal(dom, dom_make_element,              "MAKE-ELEMENT")
defexternal(dom, dom_make_text,                 "MAKE-TEXT")
// [DOM N]
definternal(dom, dom_name,                      "NAME")
definternal(dom, dom_named_node,                "NAMED-NODE")
defexternal(dom, dom_named_node_map,            "NAMED-NODE-MAP")
definternal(dom, dom_name_object,               "NAME-OBJECT")
defexternal(dom, dom_namespace,                 "NAMESPACE")
defexternal(dom, dom_namespace_error,
    "NAMESPACE-ERROR" )
defexternal(dom, dom_namepace_uri,              "NAMESPACE-URI")
defexternal(dom, dom_next_sibling,              "NEXT-SIBLING")
defexternal(dom, dom_node,                      "NODE")
defexternal(dom, dom_node_list,                 "NODE-LIST")
definternal(dom, dom_node_iterator,             "NODE-ITERATOR")
defexternal(dom, dom_node_name,                 "NODE-NAME")
defexternal(dom, dom_node_value,                "NODE-VALUE")
defexternal(dom, dom_no_modification_allowed,
    "NO-MODIFICATION-ALLOWED" )
defexternal(dom, dom_not_found,
    "NOT-FOUND" )
// [DOM O]
defexternal(dom, dom_owner_document,            "OWNER-DOCUMENT")
defexternal(dom, dom_owner_element,             "OWNER-ELEMENT")
// [DOM P]
defexternal(dom, dom_parent_node,               "PARENT-NODE")
definternal(dom, dom_prefix,                    "PREFIX")
defexternal(dom, dom_previous_sibling,          "PREVIOUS-SIBLING")
defexternal(dom, dom_processing_instruction,    "PROCESSING-INSTRUCTION")
// [DOM Q]
definternal(dom, dom_qualified_name,            "QUALIFIED-NAME")
definternal(dom, dom_qualified_table,           "QUALIFIED-TABLE")
// [DOM R]
defexternal(dom, dom_remove_child,              "REMOVE-CHILD")
defexternal(dom, dom_replace_child,             "REPLACE-CHILD")
// [DOM S]
defexternal(dom, dom_serialize,                 "SERIALIZE")
// [DOM T]
defexternal(dom, dom_text,                      "TEXT")
defexternal(dom, dom_text_content,              "TEXT-CONTENT")
// [DOM W]
defexternal(dom, dom_wrong_document,            "WRONG-DOCUMENT")
// EOF
